import './src/styles/normalize.css'
import './src/styles/style.css'

// import '@fontsource/roboto'
// import '@fontsource/noto-sans'
// import '@fontsource/noto-sans-jp'
// import '@fontsource/noto-serif'
// import '@fontsource/noto-serif-jp'
// import '@fontsource/source-sans-pro'
// import '@fontsource/raleway'
